# Development project infrastructure generated over the Docker
services:
  # Nginx
  server:
    volumes:
      - app:/app:nocopy
      - ./environment/docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf

  # PHP-FPM with WP dependencies
  wordpress:
    volumes:
      - app:/app:nocopy

  # WP CLI
  wp:
    volumes:
      - app:/app:nocopy

  # Node 8.2 with NPM/Yarn/npx
  assets-node:
    volumes:
      - app:/app:nocopy

  # PHPQA
  phpqa:
    volumes:
      - app:/app:nocopy

  # Deployer
  deployer:
    volumes:
      - app:/app:nocopy

volumes:
  app:
    name: ${VOLUME_PREFIX}app_sync
    external: true
