# Development project infrastructure generated over the Docker
services:
  # Base
  base:
    extends:
      file: common-services.yaml
      service: base
    working_dir: /app

  wordpress-base:
    extends:
      file: common-services.yaml
      service: wordpress-base
    working_dir: /app

  installer:
    extends:
      file: common-services.yaml
      service: installer

  # MySQL
  db:
    extends:
      file: common-services.yaml
      service: db

  # NGINX
  server:
    extends:
      file: common-services.yaml
      service: server

  # PHP-FPM with WP dependencies
  wordpress:
    extends:
      file: common-services.yaml
      service: wordpress
    depends_on:
      - db
      - smtp

  # WP CLI
  wp:
    extends:
      file: common-services.yaml
      service: cli

  # Node 20 with NPM/Yarn/npx
  assets-node:
    extends:
      file: common-services.yaml
      service: assets-node

  # PHPQA
  phpqa:
    extends:
      file: common-services.yaml
      service: phpqa

  # Test SMTP server
  smtp:
    extends:
      file: common-services.yaml
      service: smtp

  # Deployer
  deployer:
    extends:
      file: common-services.yaml
      service: deployer

  # Xdebug profiling viewer
  webgrind:
    extends:
      file: common-services.yaml
      service: webgrind

volumes:
  mysql_data:
