# Development project infrastructure generated over the Docker
services:
  # MySQL
  testdb:
    extends:
      file: common-services.yaml
      service: db
    volumes:
      - test_mysql_data:/var/lib/mysql:z

  # Nginx
  testserver:
    extends:
      file: common-services.yaml
      service: server
    environment:
      WORDPRESS: testwordpress
    links: !override
      - testwordpress
    volumes:
      - ./environment/docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:z
      - ./environment/docker/nginx/etc/templates:/etc/nginx/templates:z

  # PHP-FPM with WP dependencies
  testwordpress:
    extends:
      file: common-services.yaml
      service: wordpress
    environment:
      DB_HOST: testdb
      WP_HOME: http://testserver
      WP_SITEURL: http://testserver/wp
    depends_on:
      - testdb

  # Codecept
  codecept:
    extends:
      file: common-services.yaml
      service: codecept
    depends_on:
      - chrome

  selenium-hub:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
    shm_size: '2gb'
    volumes:
      - /dev/shm:/dev/shm
      - ./:/app
    depends_on:
      - selenium-hub
      - testserver
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

volumes:
  test_mysql_data:
    name: ${VOLUME_PREFIX}test_mysql_data
