# Development project infrastructure generated over the Docker
version: "3.8"

services:
  # MySQL
  testdb:
    extends:
      file: common-services.yml
      service: db
    volumes:
      - test_mysql_data:/var/lib/mysql:z

  # Nginx
  testserver:
    extends:
      file: common-services.yml
      service: server
    environment:
      WORDPRESS: testwordpress
    links: !override
      - testwordpress
    volumes:
      - ./environment/docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:z
      - ./environment/docker/nginx/etc/templates:/etc/nginx/templates:z

  # PHP-FPM with WP dependencies
  testwordpress:
    extends:
      file: common-services.yml
      service: wordpress
    environment:
      DB_HOST: testdb
      WP_HOME: http://testserver
      WP_SITEURL: http://testserver/wp
    depends_on:
      - testdb

  # Codecept
  codecept:
    extends:
      file: common-services.yml
      service: codecept
    depends_on:
      - chrome

  selenium-hub:
    image: selenium/hub:3.141.59

  chrome:
    image: selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
      - testserver
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

volumes:
  test_mysql_data:
    name: ${VOLUME_PREFIX}test_mysql_data
