# Development project infrastructure generated over the Docker
version: "3.7"

services:
  # MySQL
  testdb:
    image: mariadb
    volumes:
      - test_mysql_data:/var/lib/mysql:z
    env_file:
      - ./env/mysql.env

  # Nginx
  testserver:
    build:
      context: ./docker/nginx
      target: development
    links:
      - testwordpress
    volumes:
      - ../:/app:z
      - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:z
      - ./docker/nginx/etc/templates:/etc/nginx/templates:z
    env_file:
      - ./env/nginx.env
      - ./env/tests.env

  # PHP-FPM with WP dependencies
  testwordpress:
    build:
      context: ./docker/wp-fpm
      target: development
    volumes:
      - ../:/app:z
    env_file:
      - ./env/app.env
      - ./env/xdebug.env
      - ./env/tests.env
    depends_on:
      - testdb

  # Codecept
  codecept:
    build:
      context: ./docker/phpqa
    depends_on:
      - chrome
    volumes:
      - ../:/app
    entrypoint: ["/app/phpqa/vendor/bin/codecept"]

  selenium-hub:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
      - testserver
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

volumes:
  test_mysql_data:
    name: ${VOLUME_PREFIX}test_mysql_data
