# Development project infrastructure generated over the Docker
version: "3.7"

services:
  # Nginx
  server:
    volumes:
      - app:/app:nocopy
      - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf

  # PHP-FPM with WP dependencies
  wordpress:
    volumes:
      - www:/app:nocopy

  # WP CLI
  wp:
    volumes:
      - www:/app:nocopy

  # Node 8.2 with NPM/Yarn/npx
  assets-node:
    volumes:
      - app:/app:nocopy

  # Composer
  inc-composer:
    volumes:
      - app:/app:nocopy
      # Map local user Composer directory with container for cache packages
      - composer_cache:/tmp/cache:nocopy

  # Composer WP packages
  wp-composer:
    volumes:
      - app:/app:nocopy
      # Map local user Composer directory with container for cache packages
      - composer_cache:/tmp/cache:nocopy

  # Composer CLI
  cli-composer:
    volumes:
      - app:/app:nocopy
      # Map local user Composer directory with container for cache packages
      - composer_cache:/tmp/cache:nocopy

  # Composer CLI
  phpqa-composer:
    volumes:
      - app:/app:nocopy
      # Map local user Composer directory with container for cache packages
      - composer_cache:/tmp/cache:nocopy

  # PHPQA
  phpqa:
    volumes:
      - app:/app:nocopy

  # Deployer
  deployer:
    volumes:
      - app:/app:nocopy

volumes:
  composer_cache:
    external: true

  app:
    name: ${VOLUME_PREFIX}app_sync
    external: true

  www:
    name: ${VOLUME_PREFIX}www_sync
    external: true
