#!/bin/bash

set -euo pipefail

cd /app/public/wp

# Install WordPress if not installed
wp core is-installed &> /dev/null || bash -c '
    # Download the WordPress with the version set on composer.json to get the core language package
    wp db create &> /dev/null || wp db reset --yes 2> /dev/null;
    wp core install --url="${WP_HOME}" --title="${WP_TITLE}" --admin_user="${WP_USER}" --admin_password="${WP_PASSWORD}" --admin_email="${WP_EMAIL}" --skip-email
';

# Activate theme
wp theme is-active ${THEME_ACTIVE} || wp theme activate ${THEME_ACTIVE}

# Set WordPress defaut language
wp site switch-language ${WP_LANG}

# Activate all plugins
wp plugin activate --all;

# Update permalink structure according to install.env
wp rewrite structure ${PERMALINK}
